domain: "atc"
using_cache: True
cache_path: "/srv/git/python-tools/cache"
start: "23/11/2020"
end: "23/11/2024"
group: "M"
title_period: "Zois"
side_title_period: "Side Zois"
file_name_period: "file Zois"
output_dir: "/srv/git/python-tools/output/"
version_output: True